import type { Daily } from "@/lib/content";

// Renders a Daily JSON to a deterministic .ts module string suitable for
// drop-in to apps/frontend/content/daily/YYYY-MM-DD.ts. Output uses the
// same shape as content/daily/2026-05-12.ts so the human edit pass is
// only voice + facts, not formatting.

function constNameForDate(date: string): string {
  // "2026-05-12" → "daily20260512"
  return "daily" + date.replace(/-/g, "");
}

function escapeString(s: string): string {
  // Use double-quoted string with standard escapes. Keep it ASCII-clean.
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
}

function quote(s: string): string {
  return `"${escapeString(s)}"`;
}

export function renderDailyModule(daily: Daily): string {
  const name = constNameForDate(daily.date);
  const lines: string[] = [];
  lines.push(`import type { Daily } from "@/lib/content";`);
  lines.push("");
  lines.push("// Auto-generated by the aggregator pipeline. Edit voice and India");
  lines.push("// takeaways before flipping status to \"published\" in lib/content.ts.");
  lines.push(`export const ${name}: Daily = {`);
  lines.push(`  date: ${quote(daily.date)},`);
  lines.push(`  title: ${quote(daily.title)},`);
  lines.push(`  intro:`);
  lines.push(`    ${quote(daily.intro)},`);
  if (daily.outro) {
    lines.push(`  outro:`);
    lines.push(`    ${quote(daily.outro)},`);
  }
  lines.push(`  status: ${quote(daily.status ?? "draft")},`);
  if (daily.sponsor) {
    lines.push(`  sponsor: { sponsorId: ${quote(daily.sponsor.sponsorId)} },`);
  }
  lines.push(`  stories: [`);
  for (const story of daily.stories) {
    lines.push(`    {`);
    lines.push(`      headline: ${quote(story.headline)},`);
    lines.push(`      source: ${quote(story.source)},`);
    lines.push(`      link: ${quote(story.link)},`);
    lines.push(`      summary:`);
    lines.push(`        ${quote(story.summary)},`);
    lines.push(`      indiaTakeaway:`);
    lines.push(`        ${quote(story.indiaTakeaway)},`);
    lines.push(`      importance: ${quote(story.importance)},`);
    lines.push(`    },`);
  }
  lines.push(`  ],`);
  lines.push(`};`);
  lines.push("");
  return lines.join("\n");
}

export function renderRegistrationHint(date: string): string {
  const name = constNameForDate(date);
  return [
    `// Add to apps/frontend/lib/content.ts:`,
    `import { ${name} } from "@/content/daily/${date}";`,
    `// ...and append to the DAILIES array.`,
  ].join("\n");
}
